name: parkingapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.3+1
  firebase_core:
  firebase_database:
  firebase_auth:
  firebase_storage:
  google_sign_in: 
  flutter_speed_dial:
  image_picker:
  flutter_staggered_grid_view:
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/

  